# Generated by Django 3.2 on 2022-10-27 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('timestamp', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('humidity', models.FloatField()),
                ('air_pressure', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('timestamp', models.DateField(blank=True, null=True)),
                ('weather_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weather.weatherstation')),
            ],
        ),
    ]
