# Generated by Django 3.2 on 2022-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dataWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True, verbose_name='Tag')),
                ('AVG_LWET200', models.FloatField(verbose_name='AVG_LWET200')),
                ('AVG_RH200', models.FloatField(verbose_name='AVG_RH200')),
            ],
        ),
    ]
