# Generated by Django 3.2 on 2022-11-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_dataweather'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['weather_station'], name='weather_wea_weather_6bf3a5_idx'),
        ),
    ]
