# Generated by Django 3.2 on 2022-11-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weather_weather_wea_weather_6bf3a5_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='weather',
            name='weather_wea_weather_6bf3a5_idx',
        ),
        migrations.AddIndex(
            model_name='weather',
            index=models.Index(fields=['timestamp'], name='weather_wea_timesta_1605aa_idx'),
        ),
    ]
