# Generated by Django 3.2 on 2022-11-02 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_auto_20221101_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='timestamp',
        ),
    ]
