# Generated by Django 3.2 on 2022-11-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_remove_weatherstation_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='timestamp',
            field=models.DateField(blank=True, null=True),
        ),
    ]
